### ISSUE TITLE
How emoji generate?

### ISSUE THREAD

**Issue by getengqing** [yunjey/domain-transfer-network-tensorflow#4]
Hello, Thanks your code sharing! I want to receive your paper result which the emoji generating, How can I do?

**Comment by yunjey** [comment]
First of all, I'm not the author of the paper. This code only provides mnist-to-svhn transfer. In order to generate an emoji, we first need the emoji dataset to train the model, but the authors didn't open it to the pubic.

**Comment by ghost** [comment]
https://github.com/davrempe/domain-transfer-net

there are some emoji datasets here.
